### ISSUE TITLE
'SAMKeychain.h' file not found

### ISSUE THREAD

**Issue by ChengChuanpu** [wozhizhizhi/flutter_getuuid#1]
'SAMKeychain.h' file not found in "FlutterGetuuidPlugin.m" when use "use_frameworks!" in Podfile.

**Comment by ChengChuanpu** [comment]
it's better put 'SAMKeychain' into podspec, as  s.dependency 'SAMKeychain'. 
<img width="767" alt="Screen Shot 2019-07-25 at 17 21 18" src="https://user-images.githubusercontent.com/5194616/61863075-80aa8e00-af01-11e9-85cb-a8f30502afd9.png">

**Comment by wozhizhizhi** [comment]
Add pod 'SAMKeychain' under Podfile "target 'Runner' do" and execute the pod install command.

**Comment by wdboss** [comment]
> Add pod 'SAMKeychain' under Podfile "target 'Runner' do" and execute the pod install command.

Have you tested it? It's not working when use "use_frameworks!" in Podfile.
