### ISSUE TITLE
获取版本号不正确呀

### ISSUE THREAD

**Issue by olderMonster** [wozhizhizhi/flutter_getuuid#3]
我看获取的好像是构建版本号啊

**Comment by wozhizhizhi** [comment]
获取的是VersionCode，如果想要获取系统SDK版本请使用FlutterGetuuid.platformSystemMark

**Comment by olderMonster** [comment]
没，我就是要获取应用的版本号。
版本号：3.0.0+1
但我获取到的是platformVersionCode = 1 这个版本不对吧

**Comment by wozhizhizhi** [comment]
+号前面是版本名称，后面是版本号,你的版本号是1
